[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
giftsol = "95tdskrYsT3f2eCQAh9GUkrZWFo8rTM8aob1BhYcCFFS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
